name: React CI/CD

on:
  push:
    branches:
      - main  # Trigger when pushing to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger for pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Run on Ubuntu, but you can choose others like 'macos-latest' or 'windows-latest'
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js 20
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Using Node.js version 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install  # This will install dependencies in your 'package.json'

      # Step 4: Run tests (optional)
      - name: Run tests
        run: npm test  # Optional step, runs tests in your React app

      # Step 5: Build the app
      - name: Build app
        run: npm run build  # Run the build command to create a production build

      # Step 6: List build directory contents (optional)
      - name: List build directory contents
        run: ls -al build/  # Verify the build folder exists and contains the output files

      # Step 7: Deploy to GitHub Pages (optional, replace this with your deployment method)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to
          folder: build     # Folder containing the production build
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
