name: React CI/CD

on:
  push:
    branches:
      - main  # Trigger when pushing to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger for pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js 20 (using Node.js 20)
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install  # This will install dependencies in your 'package.json'

      # Step 4: Run tests (optional)
      # Uncomment the next lines if you want to run tests
      # - name: Run tests
      #   run: npm test

      # Step 5: Build the app
      - name: Build app
        run: npm run build  # Runs 'vite build', which generates the 'dist/' directory

      # Step 6: List build directory contents (optional)
      - name: List dist directory contents
        run: ls -al dist/  # Verify the dist folder exists and contains the output files

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to
          folder: dist      # Folder containing the production build (Vite uses 'dist')
          token: ${{ secrets.GH_TOKEN }}  # Use the custom PAT for authentication
